# =============================================================================
# roles/rhel-base/handlers/main.yml
# =============================================================================

- name: "reload shell"
  ansible.builtin.shell: "source {{ dev_home }}/.bashrc"
  listen: "reload shell"
