#!/usr/bin/env bash
# bump-versions.sh — propose version-pin bumps for makefile/versions.mk.
# Runs check-updates (porcelain) and, for each SIMPLE single-location pin that has
# drifted, bumps it in versions.mk. The dual/triple-edit pins (helix, jetbrains-
# mono, ccstatusline) are reported, never auto-edited (they need a SHA recompute /
# multi-file edits, and check-invariants.sh guards their consistency).
#
# Used by .github/workflows/version-bumps.yml (weekly) and runnable locally.
# Writes a Markdown summary to $BUMP_SUMMARY_FILE (default /tmp/bump-summary.md)
# for the PR body. Exits 0 (report tool); the caller decides if anything changed.
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT" || exit

VERSIONS="makefile/versions.mk"
SUMMARY="${BUMP_SUMMARY_FILE:-/tmp/bump-summary.md}"

# Dual/triple-edit pins — reported, never auto-edited.
EXCLUDE="HELIX_VERSION JETBRAINSMONO_NERD_VERSION CCSTATUSLINE_VERSION"

bumped=""; manual=""; skipped=""

updates=$(CHECK_UPDATES_PORCELAIN=1 \
            make -s --no-print-directory -C makefile check-updates MODE=prod 2>/dev/null \
          | grep '^update|' || true)

while IFS='|' read -r _ name detail; do
  [ -n "${name:-}" ] || continue
  old="${detail%% *}"          # "old → new" -> "old"
  new="${detail##* }"          # "old → new" -> "new"
  var="$(printf '%s' "$name" | tr '[:lower:]-' '[:upper:]_')_VERSION"
  old_re="${old//./\\.}"

  case " $EXCLUDE " in
    *" $var "*)
      manual="${manual}- \`$var\` ($name): $old → $new — needs SHA/multi-file edit (manual)\n"
      continue ;;
  esac

  if grep -qE "^${var}[[:space:]]*:=[[:space:]]*${old_re}[[:space:]]*\$" "$VERSIONS"; then
    sed -i -E "s|^(${var}[[:space:]]*:=[[:space:]]*)${old_re}[[:space:]]*\$|\1${new}|" "$VERSIONS"
    bumped="${bumped}- \`$var\` ($name): $old → $new\n"
  else
    skipped="${skipped}- \`$var\` ($name): reported $old → $new but no matching pin line (manual)\n"
  fi
done <<< "$updates"

{
  echo "## Automated version-pin bumps"
  echo
  if [ -n "$bumped" ];  then echo "### Bumped in \`makefile/versions.mk\`"; echo; printf '%b' "$bumped";  echo; fi
  if [ -n "$manual" ];  then echo "### Manual bump available (not auto-edited)"; echo; printf '%b' "$manual"; echo; fi
  if [ -n "$skipped" ]; then echo "### Skipped (could not map safely)"; echo; printf '%b' "$skipped"; echo; fi
  [ -n "$bumped$manual$skipped" ] || echo "All pins up to date — nothing to bump."
  echo
  echo "_Generated by \`scripts/bump-versions.sh\`. Each bumped pin reinstalls on next \`make provision\` (version baked into the stamp). Review before merge._"
} | tee "$SUMMARY"
