#!/usr/bin/env bash
# gen-mise-config.sh — render the mise tool declarations from makefile/versions.mk
# into chezmoi/dot_config/mise/conf.d/{workstation,workstation-dev}.toml.
#
# The two files are GENERATED (never hand-edited): versions.mk stays the single
# source of every pin, and both Linux (`make mise-runtimes` seeds them, chezmoi
# deploys them) and Windows (chezmoi deploys them, bootstrap.ps1 runs `mise
# install`) consume the same bytes. Plain TOML — not templates — so Make can
# read them before dotfiles exist on a virgin host.
#
# Run by .claude/hooks/sync-tool-memory.sh on makefile edits, by
# scripts/bump-versions.sh after a bump, and by scripts/check-invariants.sh
# (drift check) against a temp OUTDIR.
#
#   OUTDIR=<dir>  override the output directory (default: the chezmoi source).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VERSIONS="$ROOT/makefile/versions.mk"
OUTDIR="${OUTDIR:-$ROOT/chezmoi/dot_config/mise/conf.d}"

mkval() {
  grep -E "^$1[[:space:]]*:=" "$VERSIONS" | head -1 |
    sed -E 's/^[^:=]*:=[[:space:]]*//; s/[[:space:]]*(#.*)?$//'
}
need() {
  local v
  v="$(mkval "$1")"
  if [ -z "$v" ]; then
    printf 'gen-mise-config.sh: %s not found in %s\n' "$1" "$VERSIONS" >&2
    exit 1
  fi
  printf '%s' "$v"
}

UV=$(need UV_VERSION)
NODE=$(need NODE_VERSION)
GO=$(need GO_VERSION)
GOPLS=$(need GOPLS_VERSION)
LUA_LS=$(need LUA_LS_VERSION)
BASEDPYRIGHT=$(need BASEDPYRIGHT_VERSION)
TS_LS=$(need TYPESCRIPT_LS_VERSION)
TS=$(need TYPESCRIPT_VERSION)
BASH_LS=$(need BASH_LS_VERSION)
YAML_LS=$(need YAML_LS_VERSION)
VSCODE_LS=$(need VSCODE_LANGSERVERS_VERSION)

banner() {
  printf '# GENERATED by scripts/gen-mise-config.sh from makefile/versions.mk — DO NOT EDIT.\n'
  printf '# Regenerated by .claude/hooks/sync-tool-memory.sh on makefile edits and by\n'
  printf '# scripts/bump-versions.sh; scripts/check-invariants.sh fails on drift.\n'
}

mkdir -p "$OUTDIR"

{
  banner
  printf '# Both-scopes runtimes (every host). Dev-only tools live in workstation-dev.toml.\n'
  printf '[tools]\n'
  printf 'uv = "%s"\n' "$UV"
} >"$OUTDIR/workstation.toml"

{
  banner
  printf '# dev_machine only — .chezmoiignore.tmpl skips this file on prod_machine.\n'
  printf '[tools]\n'
  printf '# The npm language servers ride node'"'"'s postinstall so typescript-language-server\n'
  printf '# finds typescript as a global sibling (separate npm: trees would break that).\n'
  printf '# A changed postinstall only re-runs when node reinstalls: lib/mise.sh forces it.\n'
  printf 'node = { version = "%s", postinstall = "npm install -g typescript-language-server@%s typescript@%s bash-language-server@%s yaml-language-server@%s vscode-langservers-extracted@%s" }\n' \
    "$NODE" "$TS_LS" "$TS" "$BASH_LS" "$YAML_LS" "$VSCODE_LS"
  printf 'go = "%s"\n' "$GO"
  printf '"go:golang.org/x/tools/gopls" = "%s"\n' "$GOPLS"
  printf 'lua-language-server = "%s"\n' "$LUA_LS"
  printf '"pipx:basedpyright" = "%s"\n' "$BASEDPYRIGHT"
} >"$OUTDIR/workstation-dev.toml"

printf 'gen-mise-config.sh: wrote %s/{workstation,workstation-dev}.toml\n' "$OUTDIR"
