#!/usr/bin/env bash
# gen-tool-memory.sh — regenerate the <!-- TOOLS:START/END --> inventory block
# in the machine-level Claude memory file from mise's single sources of truth
# (config.toml / config.linux.toml / config.dev.toml [tools] tables) plus the
# handful of pins Make still owns directly (makefile/versions.mk), and the dnf
# package lists (makefile/packages.mk).
#
# Run by .claude/hooks/sync-tool-memory.sh on config*.toml/versions.mk edits,
# and by scripts/check-invariants.sh (drift check) against a temp MEMFILE.
#
#   MEMFILE=<path>  override the target file (default: the chezmoi source).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MK="$ROOT/makefile"
MEMFILE="${MEMFILE:-$ROOT/chezmoi/private_dot_claude/CLAUDE.md}"

[ -f "$MEMFILE" ] || {
  printf 'gen-tool-memory.sh: no memory file at %s\n' "$MEMFILE" >&2
  exit 1
}

# TOML parsing needs tomllib: EL9's python3 is 3.9 (no tomllib) — prefer the
# python-env wpy (3.14); CI's python3 is 3.11+. Hard-fail (not soft-skip) when
# neither exists: unlike check-invariants.sh's drift check, this generator has
# no fallback output to fall back to.
PY=""
for _p in wpy python3; do
  if command -v "$_p" >/dev/null 2>&1 && "$_p" -c 'import tomllib' 2>/dev/null; then
    PY="$_p"
    break
  fi
done
if [ -z "$PY" ]; then
  printf 'gen-tool-memory.sh: no python with tomllib on PATH (tried wpy, python3) — cannot read config*.toml\n' >&2
  exit 1
fi

# VAR -> display name for the pins Make still owns directly (versions.mk).
# Every other tool pin now lives in config.toml/config.linux.toml/config.dev.toml,
# read straight from the TOML by the python block below.
declare -A NAMES
NAMES[CLAUDE_VERSION]="claude"
NAMES[DOZZLE_VERSION]="dozzle"
NAMES[JETBRAINSMONO_NERD_VERSION]="nerd-fonts"
NAMES[VCPKG_VERSION]="vcpkg"
NAMES[PYTHON_VERSION]="python-env"

emit_block() {
  printf '<!-- TOOLS:START — auto-generated by scripts/gen-tool-memory.sh; do not edit inside -->\n'
  printf '<!-- regenerated on config*.toml/versions.mk edits by .claude/hooks/sync-tool-memory.sh; run `cza` to deploy -->\n'

  # 1-3. Sections straight from mise's [tools] tables (config.toml,
  # config.linux.toml, config.dev.toml) — the tool-pin source of truth.
  "$PY" - "$ROOT" <<'PY'
import sys, tomllib

root = sys.argv[1]


def short_name(name):
    if name.startswith("github:"):
        rest = name[len("github:") :]
        return rest.split("/", 1)[1] if "/" in rest else rest
    if name.startswith("go:"):
        return name[len("go:") :].rsplit("/", 1)[-1]
    for pfx in ("http:", "pypi:", "pipx:", "npm:"):
        if name.startswith(pfx):
            return name[len(pfx) :]
    return name


def fmt_version(spec):
    return spec.get("version", "?") if isinstance(spec, dict) else spec


sections = [
    ("Cross-platform tools (config.toml)", "config.toml"),
    ("Linux toolbelt, both scopes (config.linux.toml)", "config.linux.toml"),
    ("Dev tools (config.dev.toml)", "config.dev.toml"),
]

for title, fname in sections:
    with open(f"{root}/{fname}", "rb") as fh:
        cfg = tomllib.load(fh)
    tools = cfg.get("tools", {})
    if not tools:
        continue
    print(f"\n### {title}")
    for name, spec in tools.items():
        print(f"- `{short_name(name)}` {fmt_version(spec)}")
        # node's postinstall carries the npm language-server sidecars as one
        # `name@version` per word — surface each as its own line.
        if name == "node" and isinstance(spec, dict) and "postinstall" in spec:
            for tok in spec["postinstall"].split():
                if "@" not in tok:
                    continue
                pkg, _, ver = tok.rpartition("@")
                if pkg and ver:
                    print(f"- `{pkg}` {ver}")
PY

  # 4. The leftover pins Make still owns directly (versions.mk).
  printf '\n### Make-owned pins (versions.mk)\n'
  local line mkvar val name
  while IFS= read -r line; do
    [[ "$line" =~ ^([A-Z][A-Z0-9_]*)[[:space:]]*:=[[:space:]]*([^[:space:]#]+) ]] || continue
    mkvar="${BASH_REMATCH[1]}"
    val="${BASH_REMATCH[2]}"
    name="${NAMES[$mkvar]:-}"
    [ -n "$name" ] || continue
    printf -- '- `%s` %s\n' "$name" "$val"
  done <"$MK/versions.mk"

  # 5. dnf optional packages (the C/C++ toolchain + general system tools).
  printf '\n### System packages (dnf, dev-only)\n'
  awk '/^LINUX_OPTIONAL_PACKAGES[[:space:]]*:=/{f=1}
       f{print}
       f && $0 !~ /\\$/{exit}' "$MK/packages.mk" |
    sed -E 's/^LINUX_OPTIONAL_PACKAGES[[:space:]]*:=//; s/\\//g' |
    tr ' ' '\n' | grep -vE '^$' | LC_ALL=C sort -u | paste -sd' ' - | sed 's/^/- /'

  # 6. dnf NFS client group — dev-only AND skipped on WSL (the IS_WSL append
  # in packages.mk). Extracted by variable name from the file text, so the
  # output is host-independent (never make-evaluated).
  printf '\n### System packages (dnf, dev-only, non-WSL)\n'
  awk '/^LINUX_NFS_PACKAGES[[:space:]]*:=/{f=1}
       f{print}
       f && $0 !~ /\\$/{exit}' "$MK/packages.mk" |
    sed -E 's/^LINUX_NFS_PACKAGES[[:space:]]*:=//; s/\\//g' |
    tr ' ' '\n' | grep -vE '^$' | LC_ALL=C sort -u | paste -sd' ' - | sed 's/^/- /'

  printf '\n<!-- TOOLS:END -->\n'
}

block="$(emit_block)"

# 7. Splice the block in place of the existing one (atomic via temp + mv).
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT
awk -v block="$block" '
  index($0, "<!-- TOOLS:START") { print block; skip=1; next }
  index($0, "<!-- TOOLS:END -->") { skip=0; next }
  !skip { print }
' "$MEMFILE" >"$tmp"
mv "$tmp" "$MEMFILE"
