#!/usr/bin/env bash
# gen-tool-memory.sh — regenerate the <!-- TOOLS:START/END --> inventory block
# in the machine-level Claude memory file from the makefile single-source-of-
# truth (versions.mk drives grouping + completeness; tools.mk + a small bespoke
# map resolve VAR -> command name; packages.mk supplies the dnf list).
#
# Run by .claude/hooks/sync-tool-memory.sh on makefile edits, and by
# scripts/check-invariants.sh (drift check) against a temp MEMFILE.
#
#   MEMFILE=<path>  override the target file (default: the chezmoi source).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MK="$ROOT/makefile"
MEMFILE="${MEMFILE:-$ROOT/chezmoi/private_dot_claude/CLAUDE.md}"

[ -f "$MEMFILE" ] || {
  printf 'gen-tool-memory.sh: no memory file at %s\n' "$MEMFILE" >&2
  exit 1
}

# 1. VAR -> command names: from tools.mk macro calls...
declare -A NAMES
while IFS= read -r line; do
  [[ "$line" =~ call[[:space:]]+(EGET_TOOL|TOOL|SOFT_TOOL|USER_TOOL),([^,]+),\$\(([A-Z0-9_]+)\) ]] || continue
  nm="${BASH_REMATCH[2]}"
  var="${BASH_REMATCH[3]}"
  NAMES["$var"]+="${NAMES["$var"]:+ }$nm"
done <"$MK/tools.mk"

# ...plus bespoke / non-macro tools (installed by Makefile targets or npm/uv/go).
NAMES[EGET_VERSION]="eget"
NAMES[NODE_VERSION]="node"
NAMES[GO_VERSION]="go"
NAMES[GOPLS_VERSION]="gopls"
NAMES[CLAUDE_VERSION]="claude"
NAMES[PWNDBG_VERSION]="pwndbg"
NAMES[VCPKG_VERSION]="vcpkg"
NAMES[DOZZLE_VERSION]="dozzle"
NAMES[JETBRAINSMONO_NERD_VERSION]="nerd-fonts"
NAMES[CCSTATUSLINE_VERSION]="ccstatusline"
NAMES[LUA_LS_VERSION]="lua-language-server"
NAMES[BASEDPYRIGHT_VERSION]="basedpyright"
NAMES[TYPESCRIPT_LS_VERSION]="typescript-language-server"
NAMES[BASH_LS_VERSION]="bash-language-server"
NAMES[YAML_LS_VERSION]="yaml-language-server"
NAMES[VSCODE_LANGSERVERS_VERSION]="vscode-langservers-extracted"

# 2. Walk versions.mk top-to-bottom, emit grouped by its `# --- Section ---`.
emit_block() {
  printf '<!-- TOOLS:START — auto-generated by scripts/gen-tool-memory.sh; do not edit inside -->\n'
  printf '<!-- regenerated on makefile edits by .claude/hooks/sync-tool-memory.sh; run `cza` to deploy -->\n'
  local section="" last=""
  while IFS= read -r line; do
    if [[ "$line" =~ ^#[[:space:]]+-+[[:space:]]+(.+[^[:space:]-])[[:space:]]+-+ ]]; then
      section="${BASH_REMATCH[1]}"
      continue
    fi
    [[ "$line" =~ ^([A-Z][A-Z0-9_]*)[[:space:]]*:=[[:space:]]*([^[:space:]#]+) ]] || continue
    local var="${BASH_REMATCH[1]}" val="${BASH_REMATCH[2]}"
    local names="${NAMES[$var]:-}"
    [ -n "$names" ] || continue
    if [ "$section" != "$last" ]; then
      printf '\n### %s\n' "$section"
      last="$section"
    fi
    local n
    for n in $names; do printf -- '- `%s` %s\n' "$n" "$val"; done
  done <"$MK/versions.mk"

  # 3. dnf optional packages (the C/C++ toolchain + general system tools).
  printf '\n### System packages (dnf, dev-only)\n'
  awk '/^LINUX_OPTIONAL_PACKAGES[[:space:]]*:=/{f=1}
       f{print}
       f && $0 !~ /\\$/{exit}' "$MK/packages.mk" |
    sed -E 's/^LINUX_OPTIONAL_PACKAGES[[:space:]]*:=//; s/\\//g' |
    tr ' ' '\n' | grep -vE '^$' | LC_ALL=C sort -u | paste -sd' ' - | sed 's/^/- /'

  # 4. dnf NFS client group — dev-only AND skipped on WSL (the IS_WSL append
  # in packages.mk). Extracted by variable name from the file text, so the
  # output is host-independent (never make-evaluated).
  printf '\n### System packages (dnf, dev-only, non-WSL)\n'
  awk '/^LINUX_NFS_PACKAGES[[:space:]]*:=/{f=1}
       f{print}
       f && $0 !~ /\\$/{exit}' "$MK/packages.mk" |
    sed -E 's/^LINUX_NFS_PACKAGES[[:space:]]*:=//; s/\\//g' |
    tr ' ' '\n' | grep -vE '^$' | LC_ALL=C sort -u | paste -sd' ' - | sed 's/^/- /'

  printf '\n<!-- TOOLS:END -->\n'
}

block="$(emit_block)"

# 5. Splice the block in place of the existing one (atomic via temp + mv).
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT
awk -v block="$block" '
  index($0, "<!-- TOOLS:START") { print block; skip=1; next }
  index($0, "<!-- TOOLS:END -->") { skip=0; next }
  !skip { print }
' "$MEMFILE" >"$tmp"
mv "$tmp" "$MEMFILE"
