#!/usr/bin/env bash
# gen-tool-memory.sh — regenerate the <!-- TOOLS:START/END --> inventory block
# in the machine-level Claude memory file from mise's single sources of truth:
# config.toml / config.linux.toml / config.dev.toml [tools] tables, the host
# pins in config.toml [vars] (+ the claude-cli rolling `latest` pin, hard-
# coded — it has no [vars] entry), and the dnf package keys in
# config.host.toml / config.native.toml.
#
# Run by .claude/hooks/sync-tool-memory.sh on config*.toml edits, and by
# scripts/check-invariants.sh (drift check) against a temp MEMFILE.
#
#   MEMFILE=<path>  override the target file (default: the dotfiles source).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MEMFILE="${MEMFILE:-$ROOT/dotfiles/claude/CLAUDE.md}"

[ -f "$MEMFILE" ] || {
  printf 'gen-tool-memory.sh: no memory file at %s\n' "$MEMFILE" >&2
  exit 1
}

# TOML parsing needs tomllib: EL9's python3 is 3.9 (no tomllib) — prefer the
# python-env wpy (3.14); CI's python3 is 3.11+. Hard-fail (not soft-skip) when
# neither exists: unlike check-invariants.sh's drift check, this generator has
# no fallback output to fall back to.
PY=""
for _p in wpy python3; do
  if command -v "$_p" >/dev/null 2>&1 && "$_p" -c 'import tomllib' 2>/dev/null; then
    PY="$_p"
    break
  fi
done
if [ -z "$PY" ]; then
  printf 'gen-tool-memory.sh: no python with tomllib on PATH (tried wpy, python3) — cannot read config*.toml\n' >&2
  exit 1
fi

emit_block() {
  printf '<!-- TOOLS:START — auto-generated by scripts/gen-tool-memory.sh; do not edit inside -->\n'
  printf '<!-- regenerated on config*.toml edits by .claude/hooks/sync-tool-memory.sh; run `wsa` to deploy -->\n'

  # 1-6, all from mise config*.toml [tools]/[vars]/[bootstrap.packages] —
  # config*.toml is the single source of truth for the whole inventory now.
  "$PY" - "$ROOT" <<'PY'
import sys, tomllib

root = sys.argv[1]


def short_name(name):
    if name.startswith("github:"):
        rest = name[len("github:") :]
        return rest.split("/", 1)[1] if "/" in rest else rest
    if name.startswith("go:"):
        return name[len("go:") :].rsplit("/", 1)[-1]
    for pfx in ("http:", "pypi:", "pipx:", "npm:"):
        if name.startswith(pfx):
            return name[len(pfx) :]
    return name


def fmt_version(spec):
    return spec.get("version", "?") if isinstance(spec, dict) else spec


sections = [
    ("Cross-platform tools (config.toml)", "config.toml"),
    ("Linux toolbelt, both scopes (config.linux.toml)", "config.linux.toml"),
    ("Dev tools (config.dev.toml)", "config.dev.toml"),
]

for title, fname in sections:
    with open(f"{root}/{fname}", "rb") as fh:
        cfg = tomllib.load(fh)
    tools = cfg.get("tools", {})
    if not tools:
        continue
    print(f"\n### {title}")
    for name, spec in tools.items():
        print(f"- `{short_name(name)}` {fmt_version(spec)}")
        # node's postinstall carries the npm language-server sidecars as one
        # `name@version` per word — surface each as its own line.
        if name == "node" and isinstance(spec, dict) and "postinstall" in spec:
            for tok in spec["postinstall"].split():
                if "@" not in tok:
                    continue
                pkg, _, ver = tok.rpartition("@")
                if pkg and ver:
                    print(f"- `{pkg}` {ver}")

# 4. Host pins Make used to own directly, now in config.toml [vars]. Order:
# python-env, nerd-fonts, vcpkg (the [vars] declaration order), then
# claude — a rolling `latest` pin with no [vars] entry, hard-coded.
with open(f"{root}/config.toml", "rb") as fh:
    cfg = tomllib.load(fh)
pin_vars = cfg.get("vars", {})
pins = [
    ("python-env", pin_vars.get("python_version", "?")),
    ("nerd-fonts", pin_vars.get("nerd_font_version", "?")),
    ("vcpkg", pin_vars.get("vcpkg_version", "?")),
    ("claude", "latest"),
]
print("\n### Host pins (config.toml [vars])")
for name, val in pins:
    print(f"- `{name}` {val}")

# 5-6. dnf package keys — config.host.toml (dev-only) and config.native.toml
# (dev-only, non-WSL), the `dnf:` prefix stripped, sorted.
pkg_sections = [
    ("System packages (dnf, dev-only)", "config.host.toml"),
    ("System packages (dnf, dev-only, non-WSL)", "config.native.toml"),
]
for title, fname in pkg_sections:
    with open(f"{root}/{fname}", "rb") as fh:
        cfg = tomllib.load(fh)
    pkgs = sorted(
        k[len("dnf:") :]
        for k in cfg.get("bootstrap", {}).get("packages", {})
        if k.startswith("dnf:")
    )
    print(f"\n### {title}")
    print("- " + " ".join(pkgs))
PY

  printf '\n<!-- TOOLS:END -->\n'
}

block="$(emit_block)"

# 7. Splice the block in place of the existing one (atomic via temp + mv).
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT
awk -v block="$block" '
  index($0, "<!-- TOOLS:START") { print block; skip=1; next }
  index($0, "<!-- TOOLS:END -->") { skip=0; next }
  !skip { print }
' "$MEMFILE" >"$tmp"
mv "$tmp" "$MEMFILE"
