#!/usr/bin/env bash
# =============================================================================
# scripts/manage-hosts.sh
#
# Menu-driven host manager. Reads hosts.conf as the single source of truth
# and regenerates:
#   - ansible/inventory/hosts.ini
#   - wezterm.lua SSH domains block
#
# Usage:
#   ./scripts/manage-hosts.sh            # interactive menu
#   ./scripts/manage-hosts.sh --sync     # sync only (no menu, use in CI)
#   ./scripts/manage-hosts.sh --list     # print current hosts and exit
# =============================================================================

set -euo pipefail

# --- Resolve repo root -------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

HOSTS_CONF="$REPO_ROOT/hosts.conf"
ANSIBLE_INVENTORY="$REPO_ROOT/ansible/inventory/hosts.ini"
WEZTERM_LUA="$REPO_ROOT/wezterm.lua"

# --- Colours -----------------------------------------------------------------
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

log()     { echo -e "${BLUE}==>${RESET} ${BOLD}$*${RESET}"; }
ok()      { echo -e "${GREEN} ✓${RESET} $*"; }
warn()    { echo -e "${YELLOW} !${RESET} $*"; }
fail()    { echo -e "${RED} ✗${RESET} $*"; exit 1; }
header()  { echo -e "\n${BOLD}${CYAN}$*${RESET}"; echo -e "${CYAN}$(printf '─%.0s' {1..50})${RESET}"; }

# =============================================================================
# PARSING
# =============================================================================

# Read hosts.conf and return non-comment, non-empty lines
read_hosts() {
  grep -v '^\s*#' "$HOSTS_CONF" | grep -v '^\s*$' || true
}

# Print a formatted table of current hosts
print_hosts() {
  local hosts
  hosts=$(read_hosts)

  if [[ -z "$hosts" ]]; then
    warn "No hosts configured yet."
    return
  fi

  printf "\n${BOLD}%-20s %-18s %-14s %-14s${RESET}\n" "NAME" "IP" "USER" "GROUP"
  printf "%-20s %-18s %-14s %-14s\n" "────────────────────" "──────────────────" "──────────────" "──────────────"
  while IFS= read -r line; do
    read -r name ip user group <<< "$line"
    printf "%-20s %-18s %-14s %-14s\n" "$name" "$ip" "$user" "$group"
  done <<< "$hosts"
  echo ""
}

# Check if a host name already exists
host_exists() {
  local name="$1"
  read_hosts | awk '{print $1}' | grep -qx "$name" 2>/dev/null
}

# =============================================================================
# GENERATORS
# =============================================================================

generate_ansible_inventory() {
  log "Regenerating ansible/inventory/hosts.ini..."

  local tmp
  tmp=$(mktemp)

  cat > "$tmp" << 'HEADER'
# =============================================================================
# ansible/inventory/hosts.ini
# AUTO-GENERATED by scripts/manage-hosts.sh — do not edit manually.
# Edit hosts.conf and run: ./scripts/manage-hosts.sh --sync
# =============================================================================
HEADER

  # Collect unique groups
  local groups
  groups=$(read_hosts | awk '{print $4}' | sort -u)

  # Write each group section
  while IFS= read -r group; do
    echo "" >> "$tmp"
    echo "[$group]" >> "$tmp"
    while IFS= read -r line; do
      read -r name ip user grp <<< "$line"
      if [[ "$grp" == "$group" ]]; then
        printf "%-20s ansible_host=%-18s\n" "$name" "$ip" >> "$tmp"
      fi
    done <<< "$(read_hosts)"
  done <<< "$groups"

  # Write group vars section (use the first group's user as default)
  local default_user
  default_user=$(read_hosts | awk 'NR==1{print $3}')

  cat >> "$tmp" << VARS

# Group vars applied to all VMs
[rhel_vms:vars]
ansible_user=${default_user}
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_python_interpreter=/usr/bin/python3
VARS

  mv "$tmp" "$ANSIBLE_INVENTORY"
  ok "ansible/inventory/hosts.ini updated ($(read_hosts | wc -l | tr -d ' ') hosts)"
}

generate_wezterm_domains() {
  log "Regenerating wezterm.lua SSH domains..."

  # Build the ssh_domains lua block
  local domains_block
  domains_block="local ssh_domains = {"$'\n'

  while IFS= read -r line; do
    read -r name ip user group <<< "$line"
    domains_block+="  {"$'\n'
    domains_block+="    name           = '${name}',"$'\n'
    domains_block+="    remote_address = '${ip}',"$'\n'
    domains_block+="    username       = '${user}',"$'\n'
    domains_block+="    multiplexing   = 'None',"$'\n'
    domains_block+="  },"$'\n'
  done <<< "$(read_hosts)"

  domains_block+="}"

  # Replace the ssh_domains block in wezterm.lua between the sentinel comments
  local tmp
  tmp=$(mktemp)

  awk -v block="$domains_block" '
    /^-- HOSTS:START/ { print; print block; skip=1; next }
    /^-- HOSTS:END/   { skip=0 }
    !skip             { print }
  ' "$WEZTERM_LUA" > "$tmp"

  mv "$tmp" "$WEZTERM_LUA"
  ok "wezterm.lua SSH domains updated ($(read_hosts | wc -l | tr -d ' ') hosts)"
}

sync_all() {
  generate_ansible_inventory
  generate_wezterm_domains
  echo ""
  ok "All configs synced from hosts.conf"
}

# =============================================================================
# CRUD OPERATIONS
# =============================================================================

add_host() {
  # Supports two calling modes:
  #
  #   Interactive (menu or --add with no args):
  #     add_host
  #
  #   Non-interactive (from bootstrap.sh or other scripts):
  #     add_host --name rhel-dev-03 --ip 10.0.0.12 --user arrush --group rhel_vms --skip-confirm
  #
  local name="" ip="" user="" group="" skip_confirm=false

  # Parse named flags if any were passed
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --name)         name="$2";         shift 2 ;;
      --ip)           ip="$2";           shift 2 ;;
      --user)         user="$2";         shift 2 ;;
      --group)        group="$2";        shift 2 ;;
      --skip-confirm) skip_confirm=true; shift   ;;
      *) warn "Unknown flag: $1"; shift ;;
    esac
  done

  # If any required field is missing, fall into interactive prompts
  if [[ -z "$name" ]]; then
    header "Add a new host"
    read -rp "  Host name (e.g. rhel-dev-03):  " name
    [[ -z "$name" ]] && fail "Name cannot be empty"
  fi

  if host_exists "$name"; then
    warn "Host '$name' already exists in hosts.conf — skipping."
    return 0
  fi

  if [[ -z "$ip" ]]; then
    read -rp "  IP / hostname:                  " ip
    [[ -z "$ip" ]] && fail "IP cannot be empty"
  fi

  if [[ -z "$user" ]]; then
    read -rp "  SSH user [arrush]:              " user
    user="${user:-arrush}"
  fi

  if [[ -z "$group" ]]; then
    read -rp "  Ansible group [rhel_vms]:       " group
    group="${group:-rhel_vms}"
  fi

  echo ""
  printf "  Adding: ${BOLD}%-20s %-18s %-14s %-14s${RESET}\n" "$name" "$ip" "$user" "$group"

  if [[ "$skip_confirm" == false ]]; then
    read -rp "  Confirm? [Y/n]: " confirm
    confirm="${confirm:-Y}"
    [[ ! "$confirm" =~ ^[Yy]$ ]] && { warn "Aborted."; return 0; }
  fi

  printf "%-20s %-18s %-14s %-14s\n" "$name" "$ip" "$user" "$group" >> "$HOSTS_CONF"
  ok "Host '$name' added to hosts.conf"
  sync_all
}

remove_host() {
  header "Remove a host"
  print_hosts

  local hosts
  hosts=$(read_hosts)
  [[ -z "$hosts" ]] && return

  read -rp "  Host name to remove: " name
  [[ -z "$name" ]] && return

  if ! host_exists "$name"; then
    warn "Host '$name' not found."
    return
  fi

  read -rp "  Remove '$name'? This cannot be undone. [y/N]: " confirm
  confirm="${confirm:-N}"

  if [[ "$confirm" =~ ^[Yy]$ ]]; then
    # Remove the line from hosts.conf (preserve comments)
    local tmp
    tmp=$(mktemp)
    grep -v "^${name}[[:space:]]" "$HOSTS_CONF" > "$tmp"
    mv "$tmp" "$HOSTS_CONF"
    ok "Host '$name' removed from hosts.conf"
    sync_all
  else
    warn "Aborted."
  fi
}

edit_host() {
  header "Edit a host"
  print_hosts

  local hosts
  hosts=$(read_hosts)
  [[ -z "$hosts" ]] && return

  read -rp "  Host name to edit: " name
  [[ -z "$name" ]] && return

  if ! host_exists "$name"; then
    warn "Host '$name' not found."
    return
  fi

  # Get current values
  local current
  current=$(read_hosts | grep "^${name}[[:space:]]")
  local cur_name cur_ip cur_user cur_group
  read -r cur_name cur_ip cur_user cur_group <<< "$current"

  echo ""
  echo -e "  Current values (press Enter to keep):"

  read -rp "  IP / hostname [$cur_ip]:         " new_ip
  new_ip="${new_ip:-$cur_ip}"

  read -rp "  SSH user [$cur_user]:            " new_user
  new_user="${new_user:-$cur_user}"

  read -rp "  Ansible group [$cur_group]:      " new_group
  new_group="${new_group:-$cur_group}"

  echo ""
  printf "  Updated: ${BOLD}%-20s %-18s %-14s %-14s${RESET}\n" "$name" "$new_ip" "$new_user" "$new_group"
  read -rp "  Confirm? [Y/n]: " confirm
  confirm="${confirm:-Y}"

  if [[ "$confirm" =~ ^[Yy]$ ]]; then
    local tmp
    tmp=$(mktemp)
    # Replace the matching line, preserve everything else
    while IFS= read -r line; do
      if echo "$line" | grep -q "^${name}[[:space:]]"; then
        printf "%-20s %-18s %-14s %-14s\n" "$name" "$new_ip" "$new_user" "$new_group"
      else
        echo "$line"
      fi
    done < "$HOSTS_CONF" > "$tmp"
    mv "$tmp" "$HOSTS_CONF"
    ok "Host '$name' updated"
    sync_all
  else
    warn "Aborted."
  fi
}

test_host() {
  header "Test SSH connection"
  print_hosts

  local hosts
  hosts=$(read_hosts)
  [[ -z "$hosts" ]] && return

  read -rp "  Host name to test (or 'all'): " name

  if [[ "$name" == "all" ]]; then
    while IFS= read -r line; do
      read -r hname hip huser _ <<< "$line"
      echo -ne "  Testing ${BOLD}$hname${RESET} ($huser@$hip)... "
      if ssh -o ConnectTimeout=5 -o BatchMode=yes "$huser@$hip" exit 2>/dev/null; then
        echo -e "${GREEN}✓ OK${RESET}"
      else
        echo -e "${RED}✗ Failed${RESET}"
      fi
    done <<< "$hosts"
  else
    if ! host_exists "$name"; then
      warn "Host '$name' not found."
      return
    fi
    local line
    line=$(read_hosts | grep "^${name}[[:space:]]")
    read -r hname hip huser _ <<< "$line"
    echo -ne "  Testing ${BOLD}$hname${RESET} ($huser@$hip)... "
    if ssh -o ConnectTimeout=5 -o BatchMode=yes "$huser@$hip" exit 2>/dev/null; then
      echo -e "${GREEN}✓ Connected successfully${RESET}"
    else
      echo -e "${RED}✗ Connection failed — check IP, user, and SSH key${RESET}"
    fi
  fi
}

# =============================================================================
# MENU
# =============================================================================

show_menu() {
  header "Workstation host manager"
  print_hosts
  echo -e "  ${BOLD}1)${RESET} Add host"
  echo -e "  ${BOLD}2)${RESET} Remove host"
  echo -e "  ${BOLD}3)${RESET} Edit host"
  echo -e "  ${BOLD}4)${RESET} Test SSH connection"
  echo -e "  ${BOLD}5)${RESET} Sync configs (regenerate inventory + wezterm.lua)"
  echo -e "  ${BOLD}6)${RESET} View hosts.conf"
  echo -e "  ${BOLD}q)${RESET} Quit"
  echo ""
  read -rp "  Choice: " choice
  echo ""

  case "$choice" in
    1) add_host ;;
    2) remove_host ;;
    3) edit_host ;;
    4) test_host ;;
    5) sync_all ;;
    6) cat "$HOSTS_CONF" ;;
    q|Q) echo "Bye."; exit 0 ;;
    *) warn "Unknown option: $choice" ;;
  esac
}

# =============================================================================
# ENTRYPOINT
# =============================================================================

# Validate hosts.conf exists
[[ -f "$HOSTS_CONF" ]] || fail "hosts.conf not found at $HOSTS_CONF"

case "${1:-}" in
  --sync)   sync_all; exit 0 ;;
  --list)   print_hosts; exit 0 ;;
  --add)    shift; add_host "$@"; exit 0 ;;
  --remove) remove_host; exit 0 ;;
  "")
    while true; do
      show_menu
    done
    ;;
  *)
    echo "Usage: $0 [--sync | --list | --add [--name N --ip I --user U --group G --skip-confirm] | --remove]"
    exit 1
    ;;
esac
