# =============================================================================
# scripts/manage-hosts.ps1
#
# Windows PowerShell equivalent of manage-hosts.sh
# Reads hosts.conf as the single source of truth and regenerates:
#   - ansible/inventory/hosts.ini
#   - wezterm.lua SSH domains block
#
# Usage:
#   .\scripts\manage-hosts.ps1              # interactive menu
#   .\scripts\manage-hosts.ps1 -Sync        # sync only
#   .\scripts\manage-hosts.ps1 -List        # print current hosts
#   .\scripts\manage-hosts.ps1 -Add -Name rhel-dev-03 -Ip 10.0.0.12 -User arrush -Group rhel_vms -SkipConfirm
# =============================================================================

[CmdletBinding()]
param(
    [switch]$Sync,
    [switch]$List,
    [switch]$Add,
    [switch]$Remove,
    [string]$Name,
    [string]$Ip,
    [string]$User     = "arrush",
    [string]$Group    = "rhel_vms",
    [switch]$SkipConfirm
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# --- Resolve paths -----------------------------------------------------------
$ScriptDir  = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot   = Split-Path -Parent $ScriptDir
$HostsConf  = Join-Path $RepoRoot "hosts.conf"
$Inventory  = Join-Path $RepoRoot "ansible\inventory\hosts.ini"
$WeztermLua = Join-Path $RepoRoot "wezterm.lua"

# --- Colours -----------------------------------------------------------------
function Write-Log   { param($msg) Write-Host "==> " -ForegroundColor Blue -NoNewline; Write-Host $msg -ForegroundColor White }
function Write-Ok    { param($msg) Write-Host " v " -ForegroundColor Green -NoNewline; Write-Host $msg }
function Write-Warn  { param($msg) Write-Host " ! " -ForegroundColor Yellow -NoNewline; Write-Host $msg }
function Write-Fail  { param($msg) Write-Host " x " -ForegroundColor Red -NoNewline; Write-Host $msg; exit 1 }
function Write-Header { param($msg) Write-Host "`n$msg" -ForegroundColor Cyan; Write-Host ("─" * 50) -ForegroundColor Cyan }

# =============================================================================
# PARSING
# =============================================================================

function Read-Hosts {
    if (-not (Test-Path $HostsConf)) { Write-Fail "hosts.conf not found at $HostsConf" }
    Get-Content $HostsConf |
        Where-Object { $_ -notmatch '^\s*#' -and $_ -notmatch '^\s*$' } |
        ForEach-Object {
            $parts = $_ -split '\s+', 4
            if ($parts.Count -ge 4) {
                [PSCustomObject]@{
                    Name  = $parts[0].Trim()
                    Ip    = $parts[1].Trim()
                    User  = $parts[2].Trim()
                    Group = $parts[3].Trim()
                }
            }
        }
}

function Test-HostExists {
    param([string]$HostName)
    $hosts = Read-Hosts
    return ($hosts | Where-Object { $_.Name -eq $HostName }).Count -gt 0
}

function Show-Hosts {
    $hosts = Read-Hosts
    if (-not $hosts) { Write-Warn "No hosts configured yet."; return }

    Write-Host ""
    Write-Host ("{0,-20} {1,-18} {2,-14} {3,-14}" -f "NAME", "IP", "USER", "GROUP") -ForegroundColor White
    Write-Host ("{0,-20} {1,-18} {2,-14} {3,-14}" -f "────────────────────", "──────────────────", "──────────────", "──────────────")
    foreach ($h in $hosts) {
        Write-Host ("{0,-20} {1,-18} {2,-14} {3,-14}" -f $h.Name, $h.Ip, $h.User, $h.Group)
    }
    Write-Host ""
}

# =============================================================================
# GENERATORS
# =============================================================================

function Invoke-GenerateInventory {
    Write-Log "Regenerating ansible/inventory/hosts.ini..."

    $hosts  = Read-Hosts
    $groups = $hosts | Select-Object -ExpandProperty Group -Unique
    $lines  = @()

    $lines += "# ============================================================================="
    $lines += "# ansible/inventory/hosts.ini"
    $lines += "# AUTO-GENERATED by scripts/manage-hosts.ps1 — do not edit manually."
    $lines += "# Edit hosts.conf and run: .\scripts\manage-hosts.ps1 -Sync"
    $lines += "# ============================================================================="

    foreach ($g in $groups) {
        $lines += ""
        $lines += "[$g]"
        foreach ($h in $hosts | Where-Object { $_.Group -eq $g }) {
            $lines += "{0,-20} ansible_host={1}" -f $h.Name, $h.Ip
        }
    }

    $defaultUser = ($hosts | Select-Object -First 1).User
    $lines += ""
    $lines += "# Group vars applied to all VMs"
    $lines += "[rhel_vms:vars]"
    $lines += "ansible_user=$defaultUser"
    $lines += "ansible_ssh_private_key_file=~/.ssh/id_ed25519"
    $lines += "ansible_python_interpreter=/usr/bin/python3"

    $lines | Set-Content -Path $Inventory -Encoding UTF8
    $count = ($hosts | Measure-Object).Count
    Write-Ok "ansible/inventory/hosts.ini updated ($count hosts)"
}

function Invoke-GenerateWezterm {
    Write-Log "Regenerating wezterm.lua SSH domains..."

    if (-not (Test-Path $WeztermLua)) { Write-Fail "wezterm.lua not found at $WeztermLua" }

    $hosts = Read-Hosts

    # Build the lua block
    $block = @("-- HOSTS:START")
    $block += "local ssh_domains = {"
    foreach ($h in $hosts) {
        $block += "  {"
        $block += "    name           = '$($h.Name)',"
        $block += "    remote_address = '$($h.Ip)',"
        $block += "    username       = '$($h.User)',"
        $block += "    multiplexing   = 'None',"
        $block += "  },"
    }
    $block += "}"
    $block += "-- HOSTS:END"

    # Read the file, replace between sentinels
    $content   = Get-Content $WeztermLua -Raw
    $newBlock  = $block -join "`n"
    $pattern   = "(?s)-- HOSTS:START.*?-- HOSTS:END"
    $replaced  = [regex]::Replace($content, $pattern, $newBlock)

    if ($replaced -eq $content) {
        Write-Warn "HOSTS:START / HOSTS:END sentinels not found in wezterm.lua — skipping."
        return
    }

    # Write back with Unix line endings to keep Lua happy
    $replaced = $replaced -replace "`r`n", "`n"
    [System.IO.File]::WriteAllText($WeztermLua, $replaced)

    $count = ($hosts | Measure-Object).Count
    Write-Ok "wezterm.lua SSH domains updated ($count hosts)"
}

function Invoke-SyncAll {
    Invoke-GenerateInventory
    Invoke-GenerateWezterm
    Write-Host ""
    Write-Ok "All configs synced from hosts.conf"
}

# =============================================================================
# CRUD OPERATIONS
# =============================================================================

function Add-Host {
    param(
        [string]$HostName  = "",
        [string]$HostIp    = "",
        [string]$HostUser  = "arrush",
        [string]$HostGroup = "rhel_vms",
        [bool]$NoConfirm   = $false
    )

    if (-not $HostName) {
        Write-Header "Add a new host"
        $HostName = Read-Host "  Host name (e.g. rhel-dev-03)"
        if (-not $HostName) { Write-Fail "Name cannot be empty" }
    }

    if (Test-HostExists $HostName) {
        Write-Warn "Host '$HostName' already exists in hosts.conf — skipping."
        return
    }

    if (-not $HostIp) {
        $HostIp = Read-Host "  IP / hostname"
        if (-not $HostIp) { Write-Fail "IP cannot be empty" }
    }

    if (-not $HostUser) {
        $input = Read-Host "  SSH user [arrush]"
        $HostUser = if ($input) { $input } else { "arrush" }
    }

    if (-not $HostGroup) {
        $input = Read-Host "  Ansible group [rhel_vms]"
        $HostGroup = if ($input) { $input } else { "rhel_vms" }
    }

    Write-Host ""
    Write-Host ("  Adding: {0,-20} {1,-18} {2,-14} {3,-14}" -f $HostName, $HostIp, $HostUser, $HostGroup) -ForegroundColor White

    if (-not $NoConfirm) {
        $confirm = Read-Host "  Confirm? [Y/n]"
        if ($confirm -and $confirm -notmatch '^[Yy]') { Write-Warn "Aborted."; return }
    }

    # Append to hosts.conf
    $line = "{0,-20} {1,-18} {2,-14} {3,-14}" -f $HostName, $HostIp, $HostUser, $HostGroup
    Add-Content -Path $HostsConf -Value $line -Encoding UTF8
    Write-Ok "Host '$HostName' added to hosts.conf"
    Invoke-SyncAll
}

function Remove-HostEntry {
    Write-Header "Remove a host"
    Show-Hosts

    $hosts = Read-Hosts
    if (-not $hosts) { return }

    $HostName = Read-Host "  Host name to remove"
    if (-not $HostName) { return }

    if (-not (Test-HostExists $HostName)) {
        Write-Warn "Host '$HostName' not found."
        return
    }

    $confirm = Read-Host "  Remove '$HostName'? This cannot be undone. [y/N]"
    if ($confirm -notmatch '^[Yy]') { Write-Warn "Aborted."; return }

    # Rewrite hosts.conf without the matching line
    $newLines = Get-Content $HostsConf | Where-Object { $_ -notmatch "^$HostName\s" }
    $newLines | Set-Content -Path $HostsConf -Encoding UTF8
    Write-Ok "Host '$HostName' removed from hosts.conf"
    Invoke-SyncAll
}

function Edit-HostEntry {
    Write-Header "Edit a host"
    Show-Hosts

    $hosts = Read-Hosts
    if (-not $hosts) { return }

    $HostName = Read-Host "  Host name to edit"
    if (-not $HostName) { return }

    if (-not (Test-HostExists $HostName)) {
        Write-Warn "Host '$HostName' not found."
        return
    }

    $current = $hosts | Where-Object { $_.Name -eq $HostName } | Select-Object -First 1

    Write-Host "`n  Current values (press Enter to keep):"

    $newIp = Read-Host "  IP / hostname [$($current.Ip)]"
    $newIp = if ($newIp) { $newIp } else { $current.Ip }

    $newUser = Read-Host "  SSH user [$($current.User)]"
    $newUser = if ($newUser) { $newUser } else { $current.User }

    $newGroup = Read-Host "  Ansible group [$($current.Group)]"
    $newGroup = if ($newGroup) { $newGroup } else { $current.Group }

    Write-Host ""
    Write-Host ("  Updated: {0,-20} {1,-18} {2,-14} {3,-14}" -f $HostName, $newIp, $newUser, $newGroup) -ForegroundColor White
    $confirm = Read-Host "  Confirm? [Y/n]"
    if ($confirm -and $confirm -notmatch '^[Yy]') { Write-Warn "Aborted."; return }

    # Rewrite hosts.conf replacing the matched line
    $newLines = Get-Content $HostsConf | ForEach-Object {
        if ($_ -match "^$HostName\s") {
            "{0,-20} {1,-18} {2,-14} {3,-14}" -f $HostName, $newIp, $newUser, $newGroup
        } else { $_ }
    }
    $newLines | Set-Content -Path $HostsConf -Encoding UTF8
    Write-Ok "Host '$HostName' updated"
    Invoke-SyncAll
}

function Test-SshConnection {
    Write-Header "Test SSH connection"
    Show-Hosts

    $hosts = Read-Hosts
    if (-not $hosts) { return }

    $target = Read-Host "  Host name to test (or 'all')"

    $toTest = if ($target -eq "all") { $hosts } else {
        $h = $hosts | Where-Object { $_.Name -eq $target }
        if (-not $h) { Write-Warn "Host '$target' not found."; return }
        $h
    }

    foreach ($h in $toTest) {
        Write-Host "  Testing $($h.Name) ($($h.User)@$($h.Ip))... " -NoNewline
        $result = ssh -o ConnectTimeout=5 -o BatchMode=yes "$($h.User)@$($h.Ip)" exit 2>&1
        if ($LASTEXITCODE -eq 0) {
            Write-Host "OK" -ForegroundColor Green
        } else {
            Write-Host "Failed" -ForegroundColor Red
        }
    }
}

# =============================================================================
# MENU
# =============================================================================

function Show-Menu {
    Write-Header "Workstation host manager"
    Show-Hosts
    Write-Host "  1) Add host"
    Write-Host "  2) Remove host"
    Write-Host "  3) Edit host"
    Write-Host "  4) Test SSH connection"
    Write-Host "  5) Sync configs"
    Write-Host "  6) View hosts.conf"
    Write-Host "  q) Quit"
    Write-Host ""
    $choice = Read-Host "  Choice"

    switch ($choice) {
        "1" { Add-Host }
        "2" { Remove-HostEntry }
        "3" { Edit-HostEntry }
        "4" { Test-SshConnection }
        "5" { Invoke-SyncAll }
        "6" { Get-Content $HostsConf }
        "q" { Write-Host "Bye."; exit 0 }
        default { Write-Warn "Unknown option: $choice" }
    }
}

# =============================================================================
# ENTRYPOINT
# =============================================================================

if (-not (Test-Path $HostsConf)) { Write-Fail "hosts.conf not found at $HostsConf" }

if ($Sync)   { Invoke-SyncAll; exit 0 }
if ($List)   { Show-Hosts; exit 0 }
if ($Remove) { Remove-HostEntry; exit 0 }

if ($Add) {
    Add-Host `
        -HostName  $Name `
        -HostIp    $Ip `
        -HostUser  $User `
        -HostGroup $Group `
        -NoConfirm:$SkipConfirm.IsPresent
    exit 0
}

# Default: interactive menu loop
while ($true) { Show-Menu }